; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BMP3XX Library @ ^2.1.6
    mikalhart/TinyGPSPlus @ ^1.0.3